### ISSUE TITLE
promise() hangs 

### ISSUE THREAD

**Issue by shaunc** [dwyl/aws-sdk-mock#113]
I seem to be successfully stubbing out a function, as the spy is called, yet the `promise()` method returned by the mock hangs rather than resolving.

My test code:
```
const sendMessageSpy = spy(() => console.log('CALLED'))

describe('start-wait', () => {
  beforeAll(() => {
    MockAWS.mock('SQS', 'sendMessage', sendMessageSpy)
  })
  afterAll(() => {
    MockAWS.restore()
  })
  it('adds event to queue', async () => {
    await startWaitFct(event1)
    const actualParams = sendMessageSpy.args[0][0]
    expect(actualParams).toEqual([{
      QueueUrl: process.env.QUEUE_URL,
      DelaySeconds: 1,
      MessageBody: event1.Records[0].Sns.Message
    }])
  })
})
```
(Testing with jest, typescript.)

The function I'm calling looks like:
```
export const startWait = handleAsync(startWaitFct)
export async function startWaitFct (event: SNSEvent) {
  const sqs = new SQS({apiVersion: '2012-11-05'})
  const defaultDelay = +(process.env.QUEUE_DELAY || 20)
  for (const rec of event.Records || []) {
    const payload = rec.Sns.Message
    const {delay = defaultDelay} = JSON.parse(payload)
    await queueMessage(sqs, payload, delay)
  }
}

/**
  * Send message to delayed queue to check later
  */
async function queueMessage (
    sqs: AWS.SQS, payload: string, delay: number) {
  await sqs.sendMessage({
    QueueUrl: process.env.QUEUE_URL,
    MessageBody: payload,
    DelaySeconds: delay
  }).promise()
  console.log('OK')
}

```
(Note that "handleAsync" is a simple wrapper to convert async function to lambda function; I'm testing the async function directly here.) The diagnostic in the spy is called:
```
  console.log test/start-wait.test.ts:55
    CALLED
```
However, the `console.log('OK')` is never called, and the test times out. Am I doing something wrong, or is this not a typical use for some reason? (using     "aws-sdk-mock": "^1.7.0")

**Comment by shaunc** [comment]
Ok ... looking into the code, the "replacement" function (spy) is required to call the callback when `promise()` is used. Probably this should be documented. 

Understanding this, its pretty easy to work around; however, I've submitted a PR to allow the spy to return a promise instead.

**Comment by alexb-uk** [comment]
@shaunc thanks for the heads up this got me stumped for a quite a while as well. I think your PR would be a great addition for new users of the library as I wasn't sure exactly where I had gone wrong initially.

For anyone else coming across this issue here is an example of how to solve inc a Sinon spy prior to the PR being merged:

```javascript
const sendSpy = sinon.spy((params, callback) => {
    callback(null, { MessageId: 'spyId' });
});

AWSMock.mock('SES', 'sendEmail', sendSpy);
```
