### ISSUE TITLE
InvalidEndpoint: AWS.CloudSearchDomain requires an explicit `endpoint' configuration option.

### ISSUE THREAD

**Issue by jruts** [dwyl/aws-sdk-mock#12]
When trying to mock out the 'search' method of ClousDearchDomain we get an invalidEndpoint exception.

```
InvalidEndpoint: AWS.CloudSearchDomain requires an explicit `endpoint' configuration option.
```

How to trigger it:

```
var csd = new AWS.CloudSearchDomain({
  endpoint: 'some endpoint',
  region: 'eu-west-1'
});
awsMock.mock('CloudSearchDomain', 'search');
```

The moment you add the aws.mock part, the error gets triggered

**Comment by nelsonic** [comment]
@jruts can you give more context/code how you are invoking it?

**Comment by jruts** [comment]
@nelsonic,  modified the description

**Comment by boyarskiy** [comment]
@nelsonic, @jruts I added PR that fixed the issue. Please check it.

**Comment by nelsonic** [comment]
@boyarskiy adding `config` parameter *should* allow us to get around this issue, please add a simple test that confirms this. thanks.

**Comment by jruts** [comment]
Fixed in https://github.com/dwyl/aws-sdk-mock/pull/14

**Comment by btburton42** [comment]
Are there any working examples of this outside of the README? I'm currently testing this and experiencing either the error above or `AWS.IotData is not a constructor`, depending on where I initialize `AWS.IotData` in the parent file?

Currently, I've got in my iotClient.js:

```js
import { IotData } from 'aws-sdk';

const interactWithIOT = (command, callback, emit) => {
  const iotdata = new IotData({ endpoint: 'XXXX.us-east-1.amazonaws.com' });
  iotdata.getThingShadow({ // ... MORE CODE HERE... // })
```

And in my iotClient.test.js:

```js
const iotClient = require('./iotClient');

const AWS = require('aws-sdk-mock');

AWS.mock('IotData', 'getThingShadow', (params, callback) => {
  callback(null, 'getThingShadow SUCCESS');
})

const iotdata = new AWS.IotData({ endpoint: GHOST_IOT_CONFIG.endpointAddress });
// if I include this line I get "AWS.IotData is not a constructor"
// if I comment it out I get "AWS.IotData requires an explicit `endpoint' configuration option"

test('getThingShadow returns current thing shadow', () => {
  expect(iotClient.interactWithIOT()).toBe(true);
})
```

Thanks for the help.
