### ISSUE TITLE
Upgrade to latest sinon

### ISSUE THREAD

**Issue by chris-armstrong** [dwyl/aws-sdk-mock#122]
As a developer I would like to use the latest version of sinon so that I can take advantage of newer assertions in its spy API (such as `spy.callCount`).

The project is currently using quite an old version of sinon which is missing alot of new spy and stub functionality.

**Comment by chris-armstrong** [comment]
Please see PR https://github.com/dwyl/aws-sdk-mock/pull/123

**Comment by nelsonic** [comment]
@chris-armstrong good plan. 👍

**Comment by kevinrambaud** [comment]
Well, I submitted PR #129 to update to 5.x.x to get rid of out of date and insecure notices.

**Comment by nelsonic** [comment]
@kevinrambaud thanks for the PR. 🥇 
`aws-sdk-mock@v3.0.0` on NPM includes latest Sinon. ✅

**Comment by MichaelPaulukonis** [comment]
Can this be closed?
