### ISSUE TITLE
TypeError: request.on is not a function when aws-sdk-mock

### ISSUE THREAD

**Issue by Swapniljani08** [dwyl/aws-sdk-mock#135]
i see request.on is not function error while using the aws-sdk-mock
Please help

lambda function : 
 var request = cloudformation.getTemplate({StackName:stackName});
       request.on('success', function(response) {
       /// code logic
 });
       request.send();

test : 
var AWS = require('aws-sdk-mock');
AWS.setSDK(path.resolve('./node_modules/aws-sdk'));

describe('handler-sucess', function(){

beforeEach(function(done){
  AWS.mock('CloudFormation', 'getTemplate', function (params, callback){
    callback(null, "Success");
  });

    done();
  });
it('Test event without RequestType', function(done){
function(callback){
        lambda.handler(thisEvent,thisContext, function(returnCode){
          console.log(returnCode);
          callback(returnCode);
        });
      }
      ],
      function(){
        //console.log("\n\n\n\formatted:\n"+addStreamSpy.getCalls()[0].args);
        //expect(responseSpy.getCalls()[0].args[2]).to.equal("FAILED")
        done();
      }
    );
  });

**Comment by abetomo** [comment]
PR is already opened. ( #94 )

**Comment by Swapniljani08** [comment]
Thank you so much for quick response ! until this gets merged, It will be great help if you can suggest any workarounds

**Comment by nelsonic** [comment]
@Swapniljani08 `aws-sdk-mock@3.1.0` includes this change. :shipit: 
@abetomo thanks again for the PR! 🎉
