### ISSUE TITLE
Mocking aws.SES not working as expected

### ISSUE THREAD

**Issue by doque** [dwyl/aws-sdk-mock#145]
I have a function in which I want to make sure that `aws.SES.sendEmail()` is called:

```
import aws from 'aws-sdk';

export default function sendEmail({ fileName, eventName }) {
  // Pin region to eu-central-1, email delivery is not available in eu-central-1
  const ses = new aws.SES({ region: 'eu-west-1' });
  const params = {
    // ...
  };

  return ses.sendEmail(params).promise();
}
```

My spec looks like this:

```

import AWS from 'aws-sdk-mock';
import { sendEmail } from '..';

describe('sendEmail()', () => {
  let spy;
  beforeAll(() => {
    spy = jest.fn(() => Promise.resolve());
    AWS.mock('SES', 'sendEmail', spy);
  });

  afterAll(() => {
    AWS.restore('SES');
  });

  test('returns a promise', () => {
    expect(
      sendEmail({
        fileName: 'file.txt',
        eventName: 'CREATED'
      })
    ).toBeInstanceOf(Promise);
    expect(spy).toHaveBeenCalled();
  });
});
```

Unfortunately, e-mails are still being sent through SES when running the tests, so it seems the mock is not working as expected.
What am I doing wrong?

**Comment by dimkir** [comment]
It seems that the core reason for this problem is that `aws-sdk-mock` has troubles finding `aws-sdk` path under some package managers eg. `yarn` (in my case) or in more exotic situations (eg. when linking  https://github.com/dwyl/aws-sdk-mock/issues/81 aws sdk). 

The solution would be to set up explicitly path to the aws-sdk as explained in #81
```js
const AWS = require('aws-sdk-mock');
const path = require('path');

// be sure to edit relative path `..` to point to where aws-sdk is in your hierarchy
AWS.setSDK(path.resolve(__dirname, '../node_modules/aws-sdk'))  
```

**Comment by doque** [comment]
Thank you! That did indeed solve my problem. I'm assuming there is trouble when co-locating your tests with the source code, especially in deeply nested directories.

**Comment by jose920405** [comment]
> ```js
> setSDK
> ```

Does not works for me 😞

**Comment by jose920405** [comment]
@dimkir 

Does not works for me 😞
