### ISSUE TITLE
Re-mocking

### ISSUE THREAD

**Issue by mkjois** [dwyl/aws-sdk-mock#15]
I think it would be useful to re-mock a method that has already been mocked. For example, in my use case, I am testing a REST API that wraps DynamoDB and for each resource endpoint I'd like to mock `DynamoDB.getItem` slightly differently.

**Comment by nelsonic** [comment]
@mkjois can you show us some pseudo-code of how you would expect this to work?

**Comment by mkjois** [comment]
Yeah, nevermind, I misinterpreted the documentation and [this test](https://github.com/dwyl/aws-sdk-mock/blob/139931b93a9b30238154472251bcd186ac8b5a28/test/index.test.js#L26).
