### ISSUE TITLE
Mock out AWS to prevent use of credentials

### ISSUE THREAD

**Issue by bmeeder22** [dwyl/aws-sdk-mock#158]
As a person testing an AWS module I don't want to need to have valid AWS credentials in order to run my tests. Currently when mocking out an AWS module (say SES) the specific module and function that I am calling is getting mocked just fine, however the AWS sdk is still checking and verifying the credentials. This is a problem on say a CI server where I do not want to have to set my AWS credentials as ENV variables just to test that a function gets called.

**Comment by JohnHeadIV** [comment]
Easy thing to do is set the AWS credentials ENV to a fake/example set. AWS even provides some. These pass (parse to valid creds) but won't work for anything. (IE including example in them)
Access Key Id: AKIAIOSFODNN7EXAMPLE
Secret Access Key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY 

This also helps when checking generating presigned keys. 

The AWS sdk does some weird stuff when it comes to the credential management.

**Comment by Xicks** [comment]
@JohnHeadIV Where did you find this information? 
I cannot find fake/example credentials anywhere.

**Comment by gordey4doronin** [comment]
### A note for future users having the same issue.
If you have the same issue i.e. observe credentials errors (error examples provided in the end of this comment), make sure you've done two things below, that should do the trick.

1. The AWS Service needs to be initialised inside the function being tested in order for the SDK method to be mocked (see readme https://github.com/dwyl/aws-sdk-mock#sinon).

```js
const AWS = require('aws-sdk')

exports.handler = function(event, context, callback) {
  const s3 = new AWS.S3()
}
```

2. Set the `aws-sdk` object explicitly (see readme https://github.com/dwyl/aws-sdk-mock#setting-the-aws-sdk-object-explicitly).

```js
const AWS = require('aws-sdk')
const AWSMock = require('aws-sdk-mock')

AWSMock.setSDKInstance(AWS)
```

---

Symptoms I have without doing the two things above are the following:

```json
"message": 'Missing credentials in config',
"errno": 'EHOSTUNREACH',
"code": 'CredentialsError',
"syscall": 'connect',
"address": '192.x.x.x',
"originalError": 'Could not load credentials from any providers'
```

```json
"message": 'Missing credentials in config',
"errno": 'EHOSTDOWN',
"code": 'CredentialsError',
"syscall": 'connect',
"address": '192.x.x.x',
"originalError": 'Could not load credentials from any providers'
```

**Comment by 21042jim** [comment]
> @JohnHeadIV Where did you find this information?
> I cannot find fake/example credentials anywhere.

https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys

**Comment by jiridanek** [comment]
Couldn't find it on ^^^, but this seems to be a current source https://docs.aws.amazon.com/STS/latest/APIReference/API_GetAccessKeyInfo.html
