### ISSUE TITLE
Expectations on mock?

### ISSUE THREAD

**Issue by allenluce** [dwyl/aws-sdk-mock#20]
If I mock the `publish` function on the `SNS` service, how can I check to see that the expected message was published? It doesn't look like the mock is returned or otherwise accessible in order to check.

**Comment by allenluce** [comment]
I guess I can get to the mock with `AWS.SNS.lastCall.returnValue.publish` but that seems a little clunky.

**Comment by nikhilaravi** [comment]
@allenluce you could do it that way but I'm not quite sure what your use case is. Can you provide an example of your test and the function you are trying to test?

**Comment by landau** [comment]
Sinon provides a lot more functionality than simply overriding a method such as "how many times a specific method was called". Returning a stub from a call to `mock` would be ideal.

**Comment by nikhilaravi** [comment]
@landau yes that would certainly be useful. I will try and make this fix!

**Comment by jcready** [comment]
If you simply insert this line [in between lines 46 & 47](https://github.com/dwyl/aws-sdk-mock/blob/master/index.js#L46-L47) then calling `AWS.mock()` would return the object which will have the `stub` property on it which you can use to test against:

```js
return services[service].methodMocks[method]
```

**Comment by allenluce** [comment]
Cool, totally works! Thanks.
