### ISSUE TITLE
License in repository doesn't match NPM

### ISSUE THREAD

**Issue by jpeddicord** [dwyl/aws-sdk-mock#21]
It seems your license here in your repository (GPLv3) doesn't match what your NPM metadata says (GPLv2). Which one is correct?

**Comment by iteles** [comment]
@jpeddicors Thanks for highlighting that! We usually go with GPLv2: https://github.com/dwyl/intellectual-property/blob/master/README.md

I'll take a look into it and get it fixed :+1:

**Comment by cheruvian** [comment]
Any progress with this?

**Comment by nelsonic** [comment]
@cheruvian @jpeddicord given that `aws-sdk` uses [**Apache 2.0**](https://github.com/aws/aws-sdk-js/blob/cb5ff41d04a7237b32ec10bcb521a974e693f6bb/package.json#L52) we think its simpler to stick with that. what are your thoughts?

**Comment by iteles** [comment]
@cheruvian Changed to Apache 2.0 as explained above. Please reopen if you don't agree.

**Comment by jpeddicord** [comment]
That sounds like it'll work. :) Thanks for clarifying.
