### ISSUE TITLE
"Using Typescript" Readme section needs updating

### ISSUE THREAD

**Issue by iamuzor** [dwyl/aws-sdk-mock#221]
I have always run into the problem in the snippet each time I use this library and it normally would take me close to an hour to figure out what I'm doing wrong.

```
    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
```

This is caused by the `aws-sdk` import statement. The documentation imports the SDK like so;
``` 
import * as AWS from "aws-sdk"
```

However, this should be imported like so;
```
import AWS from "aws-sdk"
```

**Comment by atrick-speedline** [comment]
We had `import * as AWS from "aws-sdk"`, and it was working fine until we recently turned on `esModuleInterop": true,` in `tsconfig.json`, which caused this "bug".

**Comment by ahderman** [comment]
Can we close this issue now that the README has been updated?

**Comment by nelsonic** [comment]
@ahderman thanks for reminding. Closing.
