### ISSUE TITLE
Function overloading is is wrong order

### ISSUE THREAD

**Issue by captain-yossarian** [dwyl/aws-sdk-mock#241]
According to TS [docs](https://www.typescriptlang.org/docs/handbook/functions.html) less specific overload should be at the end.

> In order for the compiler to pick the correct type check, it follows a similar process to the underlying JavaScript. It looks at the overload list and, proceeding with the first overload, attempts to call the function with the provided parameters. If it finds a match, it picks this overload as the correct overload. For this reason, it’s customary to order overloads from most specific to least specific.

Please see this [file](https://github.com/dwyl/aws-sdk-mock/blob/master/index.d.ts)

Problem is in `mock` function.

![Untitled](https://user-images.githubusercontent.com/16646733/122669952-cc364700-d1bf-11eb-871b-35fb3ac3b4d8.png)
Third argument should be infered as a function but instead it has been infered to `any`

**Comment by nelsonic** [comment]
Hi @captain-yossarian thanks for opening this issue and including a screenshot from VSCode. 🏅 
The page you've linked to to: https://www.typescriptlang.org/docs/handbook/functions.html has a deprecation notice:
<img width="1395" alt="typscript-functions-page-deprecated" src="https://user-images.githubusercontent.com/194400/122724296-b1b9a780-d26b-11eb-8572-7fc93e0d522b.png">

Thankfully the **`new`** handbook page that replaces it has even more detail: 🎉 
https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads

![image](https://user-images.githubusercontent.com/194400/122725168-9ef3a280-d26c-11eb-8ff9-557bddb3ef0d.png)

![image](https://user-images.githubusercontent.com/194400/122727790-5689b400-d26f-11eb-85f6-b4b97eb34ee0.png)

![image](https://user-images.githubusercontent.com/194400/122728958-8eddc200-d270-11eb-9455-05eba2ab992b.png)

Thanks that was a good morning read; I learned how Typescript handles overloading:
https://stackoverflow.com/questions/13212625/typescript-function-overloading

# 🙂

**Comment by nelsonic** [comment]
Fixed by #242. Published to NPM: `aws-sdk-mock@5.2.1` 📦 :shipit: 
Thanks again @captain-yossarian ⭐

**Comment by captain-yossarian** [comment]
@nelsonic btw, this issue comes from SO [question](https://stackoverflow.com/questions/67920168/how-to-type-a-standalone-object-in-typescript/68054836#68054836)

**Comment by nelsonic** [comment]
FYI: https://github.com/dwyl/aws-sdk-mock/invitations
Up-voted your SO answer. Very detailed. 👍

**Comment by captain-yossarian** [comment]
@nelsonic thanks a lot!
