### ISSUE TITLE
'on' mocked method does not allow chained calls

### ISSUE THREAD

**Issue by GabrielLomba** [dwyl/aws-sdk-mock#244]
The mocked `on` method, defined [here](https://github.com/dwyl/aws-sdk-mock/blob/071b251ec849707dfe33966472dbb9d5fbcea2b3/index.js#L183) does not return `this`, which makes chained calls, such as the one below, impossible:

```
s3.getObject()
    .on('httpHeaders', ()=>{ /* some code */ })
    .createReadStream()
```

This is a simple fix. I'm willing to submit a PR for it.

**Comment by nelsonic** [comment]
@GabrielLomba thanks for opening this issue. 👍 
if you can create a PR, please do. Please ensure you add unit test(s) and ideally a few lines of docs for the `README.md` so other people are aware of the use-case. Thanks.
