### ISSUE TITLE
Can not mock SQS

### ISSUE THREAD

**Issue by ta3113ta** [dwyl/aws-sdk-mock#247]
The same problem [Here](https://stackoverflow.com/questions/57585620/how-to-mock-aws-sqs-call-for-unit-testing)
wondering why cannot mock it

**Comment by jolo-dev** [comment]
Yes, it would be nice to make any progress on this on this one.

**Comment by thomaux** [comment]
@ta3113ta the issue reported in the StackOverflow question was caused by the fact the OP had initialised the SQS service outside of the handler function. I have added a detailed [answer](https://stackoverflow.com/a/70112261/466761) on the question you linked.

**Comment by ta3113ta** [comment]
@thomaux Thank you, but it doesn't work well with **jest**
