### ISSUE TITLE
Missing region in config despite explicitly providing region

### ISSUE THREAD

**Issue by FaresKi** [dwyl/aws-sdk-mock#251]
I'm currently attempting to mock the AWS SecretsManager for my unit testing but am facing some weird errors.
My lambda calls a `utils.ts` that contains a function like this : 
```ts
//utils.ts
export const randomMethod = async (a: string, b: string) => {
  let secret
  const personalToken = {
    SecretId: process.env.secretId,
  }
  await secretManagerClient
    .getSecretValue(personalToken, (err, data) => {
      if (err) {
        console.error(`[SECRETS MANAGER] Error fetching personal token : ${err}`)
      } else if (data && data.SecretString) {
        secret = data.SecretString
      }
    })
    .promise()
  ...
}
```
Which is used by my lambda:
```ts
//lambda.ts
import {randomMethod} from 'utils.ts'
...
const response = await randomMethod(a, b)
...
export const handler: APIGatewayProxyHandlerV2 = async (event: any) => {}
``` 

And this is my mocking:
```ts
const AWS = require("aws-sdk")
const AWSMock = require("aws-sdk-mock")
afterEach(() => {
    AWSMock.restore()
  })

it("should pass", async () => {
    AWS.config.update({ region: process.env.REGION })
    AWSMock.setSDKInstance(AWS)
    AWSMock.mock("SecretsManager", "getSecretValue", () => {
      return {
        SecretString: process.env.GITHUB_PERSONAL_TOKEN_VALUE,
      }
    })
    const result = await handler(happyEvent)
    console.log("result", JSON.parse(result.body))
  })
```
And everytime I get hit with the `ConfigError: Missing region in config`... Could anyone enlighten me on what the problem could be?

**Comment by thomaux** [comment]
Hi @FaresKi, the issue is you are initialising the secrets manager before the mock can be applied. Assuming you are using Jest update your test file to reset the modules before each test and only import the SDK after this reset:

```javascript
beforeEach(() => {
	// import the aws-sdk after the resetModules, but before each test.
	jest.resetModules();
	AWSMock.setSDKInstance(require('aws-sdk'));
});
```

**Comment by FaresKi** [comment]
Thanks @thomaux !

**Comment by yourfavoritedev** [comment]
Thanks @thomaux ! This saved me a ton of time.

**Comment by brightcove-alfredo** [comment]
I can't make it work. I don't if it's because I'm initializing my AWS instance in a constructor: 
```
constructor(params) {
    this.#client = new AWS.DynamoDB.DocumentClient(params);
    this.#instance = new AWS.DynamoDB(params);
  }
```

**Comment by thomaux** [comment]
@brightcove-alfredo how are you initialising the class with that constructor? Can you show us the relevant code of your test file?

**Comment by brightcove-alfredo** [comment]
Hi @thomaux I made it work by getting an instance inside the test flow, if the singleton class was instantiated outside the code flow, lets say when imported at the top of the file then it wasn't working.

I had the code like this:

```
module.exports = new DBConnector({
  endpoint: config.env.database,
  region: config.env.aws_region
});

and then importing:
const dbConnector = require('../lib/dbConnector');
```

Now I have it this way:

```
module.exports = () => {
  return new DBConnector({
    endpoint: config.env.database,
    region: config.env.aws_region
  });
};

const dbConnector = require('../lib/dbConnector');

// inside my function
const db = dbConnector();
```

**Comment by thomaux** [comment]
Hey @brightcove-alfredo thanks for sharing your code. As before you were testing your class as a singleton, the DBConnector was already created at the time you would call the mock library. As such, the mocks could not overwrite the actual SDKs.

You could still obtain a singleton approach by updating your current solution to:

```javascript
let instance;

module.exports = () => {
    if (!instance) {
        instance = new DBConnector({
            endpoint: config.env.database,
            region: config.env.aws_region
        });
    }
    return instance;
};

const dbConnector = require('../lib/dbConnector');

// inside my function
const db = dbConnector();
```
