### ISSUE TITLE
[Feature request] Set test framework stub as default replace function and return it from mock function

### ISSUE THREAD

**Issue by thomaux** [dwyl/aws-sdk-mock#254]
This is just an idea that I would first like to discuss here. I recently launched PR https://github.com/dwyl/aws-sdk-mock/pull/253, which (if merged) enables users to use a sinon stub or jest mock as the value for the replace function.

I would like to expand on this idea by introducing a "default test stub" option. When this option is set, the user does not need to create the sinon spy, jest mock, or whatever programmable construct their choice of test framework offers, themselves. Rather, the library would create a replace function based on this "default test stub" option and use this as the return value of the mock function

So this:
```javascript
const mock = jest.fn();
awsSdkMock.mock('SNS', 'publish', mock);
```

Could be rewritten as:
```javascript
awsSdkMock.setDefaultTestStub(jest.fn);
const mock = awsSdkMock.mock('SNS', 'publish');
```

This doesn't look like a huge improvement from the snippet above, but in scenarios where you need to mock out a lot of services and methods, it greatly reduces your test setup code.

**Comment by nelsonic** [comment]
@thomaux yeah, we can see how this would be useful in a large test suite. 💡

**Comment by nelsonic** [comment]
@thomaux FYI: `aws-sdk-mock@5.5.0` published to NPM contains this update. 📦 
Thanks again. ☀️
