### ISSUE TITLE
Chore: Update package `version` 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-sdk-mock#287]
We need to release a new version of the package to ship the feature added by @proydenko94 in https://github.com/dwyl/aws-sdk-mock/pull/282  
(apologies for delay, didn't get a notification ... 🤦‍♂️)

# Todo

+ [x] Follow the instructions to publish a new version of this package to `NPM`

These are _super-manual_ the steps I follow:

1. `git checkout main` then `git pull` then 
2. `git checkout -b 'update-package-version-issue-#287'` create a new branch with a descriptive name
3. Open the `package.json` file in editor e.g. `vim package.json`
4. Update the version number in the `package.json` file e.g: 
https://github.com/dwyl/aws-sdk-mock/blob/34693d893a538297c83742f8d2355bcac0681202/package.json#L3
from `5.8.0` -> `5.9.0` 
5. Save the file.
6. Create a commit e.g: `git commit -am 'Bump version 5.8.0 -> 5.9.0 to release Mocked service abort call thanks to @proydenko94 #282'`
7. Create a new `git tag` (that is used for the release) e.g: `git tag -a 'v5.9.0' -m 'Add Mocked Service Call #282'`
8. Push both the commit and the tag to GitHub: `git push && git push --tags`
9. Create a PR with the update & assign to me. 🙏 
10. Once the PR is merged, run: `npm publish` (in the directory of the project) and enter your OTP.

Alternatively, you can run: [`npm version minor -m 'Commit Message'`](https://docs.npmjs.com/cli/v9/commands/npm-version) if you are already familiar with the above steps and want a shortcut.

**Comment by rphippswiley** [comment]
Hi @nelsonic , could we get a new version release with this `abort` call, please?

**Comment by nelsonic** [comment]
@rphippswiley thanks for reminder. 👌 
New version published: `aws-sdk-mock@5.9.0` 📦 🚀

**Comment by nelsonic** [comment]
Done. ✅

**Comment by rphippswiley** [comment]
Thank you for publishing it 👍
