### ISSUE TITLE
SES is undefined

### ISSUE THREAD

**Issue by gfogle** [dwyl/aws-sdk-mock#30]
In trying to use this mock sdk for SES, I seem to be getting undefined for that particular service.

**Comment by nelsonic** [comment]
@gfogle can you share some code for how you tried to use it? (*thanks*!)

**Comment by gfogle** [comment]
sure!

i've got a mocha test file that looks like this:
```
'use strict'

var util = require('util');

describe('Invite', function() {
  let Invite;
  let mockAWS = require('aws-sdk-mock');
  let expect = require('chai').expect;

  describe('sendInitialConfirmationEmail', function() {

    beforeEach(function() {
      global.BunyanLogger = console;
      global.AWS = require('aws-sdk');

      mockAWS.mock('SES', 'sendEmail', function (params, callback){
        callback(null);
      });

      Invite = require('./Invite');
    });

    afterEach(function() {
      mockAWS.restore('SES', 'sendEmail');
    });

    it('should return an error if no email provided', function(done) {
      Invite.sendInitialConfirmationEmail('', function(err) {
        if (err) {
          done();
        } else {
          done(new Error('test case did not pass'));
        }
      });
    });
});
```

and that throws the error of cannot `restore` undefined

**Comment by wedgybo** [comment]
Did you ever find the cause? I'm running into a similar issue.

**Comment by jruts** [comment]
@gfogle can you try to do `mockAWS.restore()` instead? Just to see what the result of that is.

**Comment by gfogle** [comment]
sorry for the delay - yes ill give that a try and finish digging into the issue this week.

**Comment by nikhilaravi** [comment]
@gfogle did you manage to try it out?

**Comment by gfogle** [comment]
no params didnt do the trick. issue seems to be that SES.sendEmail does not have a `stub` property. its undefined here: https://github.com/dwyl/aws-sdk-mock/blob/master/index.js#L177

**Comment by jruts** [comment]
@gfogle , https://github.com/dwyl/aws-sdk-mock/pull/34/files should be an answer to your problems. Make sure to check it  out when we merge it in!
