### ISSUE TITLE
s3.getSignedUrl('getObject', params);

### ISSUE THREAD

**Issue by nicka** [dwyl/aws-sdk-mock#31]
I don't get mock `s3.getSignedUrl('getObject', params);`. I tried it with nested. But `getSignedUrl` is not a nested class.

What I tried so far:
```js
beforeEach(function() {
  let headObjectParams = {
    Bucket: 'mockedBucket',
    Key: testEvent.body.id
  };

  AWS.mock('S3', 'headObject', function(headObjectParams, callback) {
    callback(null, {});
  });

  let getSignedUrlParams = {
    Bucket: 'mockedBucket',
    Key: testEvent.body.id,
    Expires: 500
  };

  AWS.mock('S3', 'getSignedUrl', 'getObject', function(getSignedUrlParams, callback) {
    callback(null, {
      data: 'https://example.com'
    });
  });
});
```

Tried:
```
AWS.mock('S3', 'getSignedUrl', 'getObject',
AWS.mock('S3', 'getSignedUrl.getObject',
AWS.mock('S3.getSignedUrl', 'getObject'
```
where `S3.getSignedUrl` was mocked before the `headObject`.

`AWS.mock('S3', 'headObject'` is working perfectly.

Link to method: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

**Comment by nikhilaravi** [comment]
@nicka from looking at the s3 docs I don't think you need to mock the 'getObject' method on 'getSignedUrl - you should only need to mock 'getSignedUrl'. 

```
AWS.mock('S3', 'getSignedUrl', function(method, callback) {
    callback(null, {
      data: 'https://example.com'
    });
  });
```

where `method` would be `getObject`. 

The third argument to `AWS.mock` is the either a string or a function which replaces the function you are mocking - in this case you are mocking `S3.getSignedUrl`. This replacement function will get passed the arguments with which the `S3.getSignedUrl` was originally invoked. 

@jruts what do you think?

**Comment by nicka** [comment]
@nikhilaravi Thanks for the quick reply. However it made no difference. Some more debug information:
```
type=INFO msg="Checking if objects exists on S3 id = s3-sample"
type=INFO msg="Object exists on S3 id = s3-sample"
type=INFO msg="Generating pre-signed url for S3 object id = s3-sample"
getObject err { [TimeoutError: Missing credentials in config]
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: Mon Jun 06 2016 13:49:03 GMT+0200 (CEST),
  originalError:
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: Mon Jun 06 2016 13:49:03 GMT+0200 (CEST),
     originalError:
      { message: 'Missing credentials in config',
        code: 'CredentialsError',
        time: Mon Jun 06 2016 13:49:03 GMT+0200 (CEST),
        originalError: [Object] } } }
type=ERROR msg="TimeoutError: Missing credentials in config"
```

**Comment by nikhilaravi** [comment]
@nicka sorry for the delay! Did you manage to resolve the issue?

Can you provide the code that you are trying to test? If the s3 instance is instantiated outside the function you are testing it might not get mocked.

**Comment by nicka** [comment]
@nikhilaravi sorry for the delay here as well haha!

>If the s3 instance is instantiated outside the function you are testing it might not get mocked.
Was definitely the case.

I finally managed to get it working with:
```
AWS.mock('S3', 'listObjects', {
    Contents: [
      { Key: 'foo.wav' }
    ]
  });
```

**Comment by nikhilaravi** [comment]
@nicka great! Glad you managed to get it working!

**Comment by Gerjunior** [comment]
I'm having the same problem but the above example didn't gave me a clue on how to make `s3.getSignedURL` work. Any other suggestions?

**Comment by Gerjunior** [comment]
Finally got it working with `await s3.getSignedUrlPromise('putObject', s3Params)`
and mocking `AWS.mock('S3', 'getSignedUrl', 'signedURL')`.
Not sure why, but it is working!
