### ISSUE TITLE
Error: Region is missing while mocking S3, getObject

### ISSUE THREAD

**Issue by SisyphusCoin** [dwyl/aws-sdk-mock#369]
Description:
Jest throw region missing error while I'm trying to mock the S3 getObject method.
Ideally S3 doesn't need region configured, can check the S3 SDK document here:
[AWS SDK DOCUMENT LINK](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_s3_code_examples.html)
Issue still exist after I setInstance before mock.

Test case:
`
    AWSMock.mock('S3', 'getObject', Buffer.from('test'));
`

Code:
`
    const s3 = new S3({});
    const stream = await s3.getObject({
      Bucket: bucketName,
      Key: keyName,
    });
`

Behavior:
Jest throw error: Error: Region is missing Jest

Versions:
"jest": "^29.7.0",
"@aws-sdk/client-s3": "^3.502.0",
"aws-sdk-mock": "^5.9.0",

**Comment by nelsonic** [comment]
You've shared a link to the `V3` SDK which this mocking library does not yet support. 
Region is required.

**Comment by SisyphusCoin** [comment]
Thanks for solving my doubt, we can close this issue I think.
@nelsonic
