### ISSUE TITLE
Mock client constructors?

### ISSUE THREAD

**Issue by rclark** [dwyl/aws-sdk-mock#38]
Sometimes I would like to be able to make assertions about the configuration options that are sent to the client constructor, e.g. region or fixed params.

How difficult would it be to expose a mechanism for mocking the constructors? e.g.

``` js
AWS.mock('S3', function(config) {
  assert.equal(config.region, 'eu-west-1');
});
```

**Comment by dcrockwell** [comment]
I would also like to assert that the correct configuration was sent.

**Comment by modmac** [comment]
Constructors are stubbed automatically, you can write assertions like this:
```JavaScript
const AWS_SDK = require('aws-sdk');

sinon.assert.calledWith(AWS_SDK.S3, { region: 'eu-west-1' });
```
