### ISSUE TITLE
Using AWS SDK promises

### ISSUE THREAD

**Issue by bdruth** [dwyl/aws-sdk-mock#43]
I'm not groking at all how to use aws-sdk-mock with AWS SDK's [promise support](https://blogs.aws.amazon.com/javascript/post/Tx3BZ2DC4XARUGG/Support-for-Promises-in-the-SDK). Can anyone provide a quick example? My code would look like:
```
  var getPromise = s3.getObject(params).promise();
  getPromise.then(function(data) {
    // ...
  });
```
What would my mock look like? Presumably there's a way to ``resolve(data)`` or something along those lines from my spec so I can return whatever data I want to test against?

Bonus points if you can show me how to hook up that promise with chai-as-promised or a sinon expectation ...

**Comment by bdruth** [comment]
I think I figured this out, I'll document what I did in a little bit.

**Comment by bdruth** [comment]
A colleague pointed out that using the AWS SDK with promises meant that the pattern of invoking the callback at the end of the lambda probably needs to be moved to be inside a then(). That looks like this (simplified)
``` 
  var getPromise = s3.getObject({}).promise();
  getPromise.then(function(data) {
    // do something with data
  }).then(function() {
    // finally, execute callback
    cb(null,
      { message: `Received event from ${event.Records[0].s3.bucket.name}`, event });
  });
```
This then works with a simple mock that returns data, e.g.:
```
    AWS.mock 'S3', 'getObject',
      body: "data"
```
So far so good, we'll see how it goes!

**Comment by tomdavidson** [comment]
@bdruth mind giving a promise counter example to the README.md example? (Im not quite following)

```js
 
var AWS = require('aws-sdk-mock');
 
AWS.mock('DynamoDB', 'putItem', function (params, callback){
  callback(null, "successfully put item in database");
});
 
AWS.mock('SNS', 'publish', 'test-message');
 
/**
    TESTS
**/
 
AWS.restore('SNS', 'publish');
AWS.restore('DynamoDB');
```

**Comment by nitrocode** [comment]
Im having issues with this too. Does anyone know of a detailed example of mocking aws-sdk promises?

**Comment by nitrocode** [comment]
@tomdavidson @bdruth did you guys ever figure this out? The callback doesn't make sense to me. I thought if you use AWS sdk's promises, why would you need to call a callback?

**Comment by hoegertn** [comment]
You always have to use the mock in the same way with the callback. But it does not care if you call the actual AWS client with callback or using promises.

**Comment by bfdykstra** [comment]
Using Sinon and an example AWS Lambda object, mock the aws promises like by returning the promise() method:
```
const sinon = require('sinon')
const lambdaInvokeStub = sinon.stub(lambda, 'invoke')
lambdaInvokeStub.returns({
        promise: () => Promise.resolve({
          StatusCode: 200,
          ExecutedVersion: '$LATEST',
          Payload: '{"Request": {"Status": "Successful",}}',
        }),
      })
```
