### ISSUE TITLE
createReadStream buffer support

### ISSUE THREAD

**Issue by MrHen** [dwyl/aws-sdk-mock#52]
I opened a PR to add .createReadStream support: https://github.com/dwyl/aws-sdk-mock/pull/50

The basic functionality is:

```
    awsMock.mock('S3', 'getObject', new Buffer('body'));
    var s3 = new AWS.S3();
    var req = s3.getObject('getObject', {});
    var stream = req.createReadStream();
    stream.pipe(concatStream(function(actual) {
      st.equals(actual.toString(), 'body')
      awsMock.restore('S3', 'getObject');
      st.end();
    }));
```

**Comment by MrHen** [comment]
@nelsonic Not sure what help is needed for this ticket. The PR is ready to go. Is there someone else I can ping who can look at this and merge it?

**Comment by MrHen** [comment]
@nikhilaravi 
@jruts 
@jcready 
@motiz88 
@nelsonic 

Sorry to ping all of you but I'm not sure which of you is the right person to ask for a merge. If no one has time or interest, feel free to add me as a contributor.

**Comment by nelsonic** [comment]
@MrHen merged and added you as a _colaborator_. (_not so that you can merge your own PRs, just so that you can review anyone `else`'s in the future and can create branches directly in the project_) 👍
