### ISSUE TITLE
"Cannot read property 'operations' of undefined" since 1.6.0

### ISSUE THREAD

**Issue by rmatec** [dwyl/aws-sdk-mock#54]
Hi,

I am getting an error whenever I try to mock a Dynamo DB query call since upgrading to 1.6.0. The error I am getting is this: TypeError: Cannot read property 'operations' of undefined.
I haven't tried other mocks except for S3 which looks to be working fine (getObject and listObjects)  so I don't know if this limited to the DynamoDB mock or the error is also affecting other areas.

Is this also occurring on your end?

**Comment by nelsonic** [comment]
@rmatec _thanks_ for raising this issue and _good question_! 
Could you please share some sample code so we can help you diagnose the issue?

**Comment by rmatec** [comment]
HI @nelsonic, thank for your quick response.

The code I have is very straightforward. I first create the mock like this:
awsMock.mock('DynamoDB.DocumentClient', 'query', (params, callback) => {
   // Some code here that is NOT invoked
}

and then I run the test which uses the mock:
let dynamoDB = new AWS.DynamoDB.DocumentClient();
dynamoDB.query(queryParams, (error, data) => { // Process code here }

I get the Dynamo DB query result in the error variable in the callback. There is where I see the error (TypeError: Cannot read property 'operations' of undefined)

Hope that helps.

**Comment by eduponte** [comment]
Hi,
I'm facing a similar issue since 1.6.0.

`TypeError: Cannot read property 'input' of undefined`

My mock being:
```
      AWS.mock('S3', 'getSignedUrl', (fnName, params, callback) => {
        const s3url = `https://s3.amazonaws.com/${params.Bucket}/${params.Key}`;
        callback(null, `${s3url}?${signatureParams}`);
      });
```

Hope that helps,
E

**Comment by nelsonic** [comment]
@rmatec thanks, that _helps_. 
This is _really_ annoying because our Travis-CI build passes for `v1.6` ... [![Build Status](https://travis-ci.org/dwyl/aws-sdk-mock.svg?branch=master)](https://travis-ci.org/dwyl/aws-sdk-mock)
sounds like we need to write a few more tests for the use-case you and @eduponte are describing.

> If anyone has _time_ to write a quick `Pull Request` with some tests it would be _much_ appreciated. thanks!

**Comment by jedatu** [comment]
Has there been any more progress on this?  If I comment out the `paramValidation`, then the error goes away.
```
    if ((client.config || _AWS.config).paramValidation) {
      try {
        var inputRules = client.api.operations[method].input;
        var outputRules = client.api.operations[method].output;
        var params = userArgs[(userArgs.length || 1) - 1];
        new _AWS.ParamValidator((client.config || _AWS.config).paramValidation).validate(inputRules, params);
      } catch (e) {
        callback(e, null);
        return request;
      }
    }
```
The `client.api` is undefined which is why the `operations` call fails.  

Does anyone know a better workaround or root cause?

**Comment by eduponte** [comment]
Hi @jedatu you are right, the issue is related to `paramValidation: true`. I have created a PR.
@nelsonic Hope it helps.

**Comment by nelsonic** [comment]
@rmatec we have _merged_ @eduponte's Pull Request. please try `aws-sdk-mock@1.6.1` and let us know if the issue is resolved. thanks! 👍

**Comment by rmatec** [comment]
Excellent, thank you very much for your help. I'll try 1.6.1 right away and let you know.

**Comment by rmatec** [comment]
Hi @eduponte ,

All my tests are back to green. Thanks everyone for your help.

**Comment by nelsonic** [comment]
@rmatec _great_ news! (_please close the issue if you are happy... and ⭐️  the repo to help spread the word_ :wink: )

**Comment by rmatec** [comment]
Closing ticket. Thanks for your help :thumbsup:

**Comment by ubatta** [comment]
rmatec,

I am getting the exactly same error, but not able to resolve. I am working on a skill to retrieve data from dynamo db based on response from user. Could you please help
