### ISSUE TITLE
How to get at the method stub?

### ISSUE THREAD

**Issue by onyxraven** [dwyl/aws-sdk-mock#56]
I want to be able to get at the method stub so I can do `stub.onCall()` but i'm unsure this is possible.

Use case:

I'm trying to mock the test for `AWS.DynamoDB.DocumentClient().writeBatch()`.  writeBatch will reply with `UnprocessedItems` for any items which were throttled during write, and it is up to the client to retry them,  So, a new call to writeBatch is required.

So, I need the first call to send some UnprocessedItems, and the second to have an empty UnprocessedItems.  

(to further complicate things, I'm using promises...)

Any help is appreciated.  I know this isn't necessarily an Issue, but maybe it results in an enhancement.

**Comment by thejuan** [comment]
AWS.mock returns an object that contains the stub.

**Comment by onyxraven** [comment]
I'm going to close this, since it wasn't answered and the question was asked so long ago I don't remember the exact context.
