### ISSUE TITLE
Attempted to wrap putObject which is already stubbed

### ISSUE THREAD

**Issue by maxtotterman** [dwyl/aws-sdk-mock#57]
Hi I'm trying to use this library, but cannot get it to work.
node: 4.3.0
"aws-sdk": "^2.5.2",
"aws-sdk-mock": "^1.5.0",

getting this error: 

>     TypeError: Attempted to wrap putObject which is already stubbed
>       at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core.js:84:29)
>       at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:128:21)
>       at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
>       at mockServiceMethod (node_modules/aws-sdk-mock/index.js:95:54)
>       at new <anonymous> (node_modules/aws-sdk-mock/index.js:80:7)
>       at Function.invoke (node_modules/sinon/lib/sinon/spy.js:172:59)
>       at proxy (eval at createProxy (node_modules/sinon/lib/sinon/spy.js:77:86), <anonymous>:1:35)
>       at Object.uploadAttachment (api/services/FileService.js:137:12)

When using my service
```
function uploadAttachment(file) {
  var s3 = new AWS.S3();
  var params = {
  ...
  };

  var upload = s3.putObject(params).promise();
  return upload
  .then(function (result) {
    return result;
  })
  .catch(function (error) {
    throw new Error(error);
  });
}
```

Test
```
it('should upload an attachment to a s3 bucket', function() {
      AWS.mock('S3', 'putObject', 'success');
      return FileService.uploadInvoiceAttachment('file.txt')
      .then(function (body) {
        body.should.be.true;
        AWS.restore();
      });
});
```

**Comment by maxtotterman** [comment]
Ah got it!

Apparently I had to have the AWS.mock() in the "global" scope of my test module.

**Comment by apoca** [comment]
@maxtotterman can you share how you solved that? I am facing the same issue:

```js
beforeAll(() => {
    AWS.mock('S3', 'putObject', 'success');
  });

  afterAll(() => {
    AWS.restore('S3');
  });
```
