### ISSUE TITLE
Mocking AWS services which are referenced in other services

### ISSUE THREAD

**Issue by thchia** [dwyl/aws-sdk-mock#64]
Thanks for this package, it's a real timesaver!

I am now using the Amazon Cognito SDK for JavaScript (amazon-cognito-identity-js).

[https://github.com/aws/amazon-cognito-identity-js](url)

This allows signup, sign in etc to a specified Cognito User Pool. The methods in this package call AWS.CognitoIdentityServiceProvider methods at various points.

How can I mock the CognitoIdentityServiceProvider methods in my tests, because I do not actually instantiate CognitoIdentityServiceProvider in my own code?

**Comment by maitriyogin** [comment]
Hi, 
I had the same problem and had to use `mock-require` and a test_helper.
test_helper :
```
const path = require('path');
const AWS = require('aws-sdk-mock');
const AWS_SDK = require('aws-sdk');
AWS.setSDK(path.resolve('./node_modules/aws-sdk'));
const mock = require('mock-require');
mock('aws-sdk', AWS_SDK);
```

package.json:
```
    "test": "./node_modules/.bin/mocha --require ./test/test_helper.js --recursive"
```

What was happening was that the js file in the referring lib (connector/connect.js) was using it's AWS-SDK in it's node_modules, not that of the referee that was under test

By using mock-require it seems to force every require in all referring libs, to use the one you specify ... and not the one in it's own project dir...
So:
app/test/test_helper
app/test/test1.js <- refers to connector/connect.js 
app/node-modules/aws-sdk

connector/connect.js <- without mock-require connect will use the connector/node-modules/aws-sdk 
connector/node-modules/aws-sdk

Hope that helps,
/Stephen.
P.S. by the way I think this is a bug ...

**Comment by thchia** [comment]
I ended up not using this library for mocking. I mocked the functions from AWS Cognito SDK in their entirety, which I found easier (and also I think makes more sense). Thanks for the input though!

**Comment by Antonio-Riccelli** [comment]
Hi @thchia, 
Sorry to dig up this old issue, but could you share more details as to how you dealt with this? I'm going through a similar problem now. Did you just recreate the methods from scratch to imitate the AWS ones? Thanks.

**Comment by thchia** [comment]
@Antonio-Riccelli it was a while ago now, but I think what I meant was that I mocked the whole `amazon-cognito-identity-js` library, instead of trying to mock one of its "inner" services. Anyway, it has since been absorbed into the Amplify ecosystem of libraries.

These days, if I am mocking the AWS SDK (e.g. in a backend service), I do it like this:

```typescript
const mockedAdminDeleteUser = jest.fn();

jest.mock("aws-sdk", () => {
  return {
    CognitoIdentityServiceProvider: class {

      // any other methods used by your code

      adminDeleteUser(...args: unknown[]) {
        mockedAdminDeleteUser(...args);
        return this;
      }

      promise() {
        return Promise.resolve({});
      }
    },
  };
});
```
I can assert on `mockedAdminDeleteUser` with any of the regular jest assertion helpers like `.toHaveBeenCalled()` etc.

**Comment by Antonio-Riccelli** [comment]
Thank you, @thchia - that's helpful.
