### ISSUE TITLE
Mock doesn't seem to be working when package is included via npm link

### ISSUE THREAD

**Issue by iwllyu** [dwyl/aws-sdk-mock#81]
I have a package DynamodbUtils that makes calls to dynamodb using aws sdk.

MyPackage installs DynamodbUtils from an private npm registry. In a test in MyPackage I mock dynamodb via
```
        awsm.mock('DynamoDB.DocumentClient', 'query', (params, callback) => {
            // console.log("querying with params: %j", params);
            callback(null, mockDynamodbResponse);
        });
```

and later call the DynamodbUtils function that will eventually call (the mocked) dynamodb. Everything works as expected. 

However if I go into DynamodbUtils and `npm link`, and then in MyPackage do `npm link DynamodbUtils` and then try to run the test, I get `ResourceNotFoundException: Requested resource not found` and the error originates comes from DynamodbUtils/node_modules/aws-sdk/lib dir, which seems like AWS is no longer being mocked appropriately.

If I use npm pack in DynamodbUtils and then install the tar in MyPackage it also seems to be mocking as expected

**Comment by damonmaria** [comment]
This will most likely be because the linked package is using its own copy of `aws-sdk`. So `node_modules/DynamodbUtils` will be a symlink to where you have the code for `DynamodbUtils`. Under *that directory* will be `node_modules/aws_sdk`. So you will need to use something like:

```js
AWS.setSDK(path.resolve('node_modules/DynamodbUtils/node_modules/aws-sdk'))
```
