### ISSUE TITLE
Is it possible to mock a service constructor

### ISSUE THREAD

**Issue by wheresrhys** [dwyl/aws-sdk-mock#89]
From the docs (and playing around a bit with the code) it looks like it's not possible to stub a constructor for a service. e.g. I only want to check which options are passed in to `AWS.DynamoDB`.

**Comment by modmac** [comment]
Constructors are stubbed automatically, you can write assertions like this:
```JavaScript
const AWS_SDK = require('aws-sdk');

sinon.assert.calledWith(AWS_SDK.DynamoDB, { apiVersion: '2012-08-10' });
```
